### ISSUE TITLE
Add implementation notes?

### ISSUE THREAD

**Issue by lassik** [schemedoc/manpages#1]
Should we add portability notes to the manpages about how different Scheme implementations handle those things? For example, string representation used in each implementation and things like that.

**Comment by lassik** [comment]
There are usually only a handful of implementation strategies for each part of the language, so we could briefly describe each strategy and then list the implementations doing that.

**Comment by lassik** [comment]
Or put that information in [guides](https://github.com/schemedoc/guides)?

I'd like to have such a guide covering all Lisp dialects under [Lisp union](https://github.com/lispunion) since the dialects face similar implementation issues.

**Comment by weinholt** [comment]
For the section 3 manpages that's the "IMPLEMENTATION NOTES" section. Did you have something particular in mind to write about?

**Comment by weinholt** [comment]
I'm writing the page for vector(3) and realized that even this seemingly innocent procedure has implementation notes. It's the type of obscure stuff they'd put on programming skill tests if Scheme was more mainstream. :)

**Comment by lassik** [comment]
Way ahead of me, you had already put in placeholders for the implementation notes! Sorry for not noticing.

**Comment by lassik** [comment]
This seems to be well underway so I'll close the issue.
