### ISSUE TITLE
Change from 3scheme to 3scm?

### ISSUE THREAD

**Issue by lassik** [schemedoc/manpages#11]
Some versions of the Unix `man` program (at least the version that ships with MacOS) do not recognize manual subsections longer than three characters.

The program thinks `man 3sch exit` refers to the page `exit` in a section starting with `3sch` whereas if you type `man 3scheme exit` it thinks you are asking for two different manual pages, first `3scheme` and then `exit`, both from any section of the manual.

For compatibility with these programs, should we change the subsection from `3scheme` and `7scheme` to `3scm` and `7scm`?

**Comment by weinholt** [comment]
Sure, no problem. I can make the change.
