### ISSUE TITLE
Use unroff to generate HTML

### ISSUE THREAD

**Issue by lassik** [schemedoc/manpages#14]
I managed to resurrect [unroff](https://conservatory.scheme.org/unroff/), which is a Scheme-scriptable troff parser. It runs using the version of Elk Scheme that ships in Debian (`apt install elk`) and produced pretty good results with little work.

I think we should ditch our [patched copy of the C program `man2html`](https://github.com/schemedoc/man2html) and patch unroff instead. It's faster and more fun, produces better output, and we'd be improving Scheme at the same time.

**Comment by lassik** [comment]
Check out how easy it was to [add manpage-to-manpage links into the HTML output](https://gitea.scheme.org/conservatory/unroff/commit/8d14fa2997056c32179ee5ceb501a800843db865) with no prior support in the codebase.

**Comment by weinholt** [comment]
Looks neat. Does it handle eqn and tbl macros?

**Comment by lassik** [comment]
[It should.](https://conservatory.scheme.org/unroff/#managing)

> In this way authors of hypertext documents can take full advantage of the usual troff facilities such as user-defined macros, conditional text, tables, equations, and drawings, automatic table of contents generation, footnotes/endnotes, indexes, etc., none of which are available when composing documents directly in plain HTML.

[Example with tables](https://conservatory.scheme.org/unroff/examples/pathconf.2.html)

**Comment by lassik** [comment]
I just regenerated man.scheme.org using unroff. Example: [`bitwise-ior`](https://man.scheme.org/bitwise-ior.3scm). The clickable links should work.

Elk segfaults on my computer with some pages, so those are missing. I'll look into it.

**Comment by lassik** [comment]
The segfault is related to `call/cc` and possibly has to do with `alloca()`.

Elk seems to run crash-free on Debian.

**Comment by lassik** [comment]
So far, so good. The work to improve HTML generation continues at https://github.com/schemeorg-community/man.scheme.org.
