### ISSUE TITLE
Publish under scheme.org

### ISSUE THREAD

**Issue by lassik** [schemedoc/manpages#3]
Should we publish HTML versions of the manpages under https://doc.scheme.org/? Mandoc or Pandoc could be a resonable converter.

**Comment by lassik** [comment]
PR #4

**Comment by lassik** [comment]
We should also upload the roff source files to the web server, so that someone at a foreign computer can `curl` one and read it on the terminal.

For a demo, I uploaded the source for `begin` so that the following command works:

```Shell
curl https://doc.scheme.org/man/begin.3scheme | nroff -man | less
```

**Comment by lassik** [comment]
If we wanted to, we could make a `man.scheme.org` subdomain for really short URLs:

```Shell
curl https://man.scheme.org/begin | nroff -man | less
```

**Comment by lassik** [comment]
Which really suggests some enterprising soul should add HTTP support to the `man` command for general awesomeness:

```Shell
man https://man.scheme.org/begin
```

or even:

```Shell
man man.scheme.org/begin
```

since local directories with dots are not that useful, and in any case, one could still disambiguate via `./foo` or `/foo`.

**Comment by weinholt** [comment]
Man pages via HTTP sounds like a potential security risk. I will package the manpages in Debian when they are more complete, and I'm sure they will make their way into other distributions.

**Comment by lassik** [comment]
Distro packaging is good.

**Comment by lassik** [comment]
Closing this issue since man.scheme.org is up. I'll add code to upload the roff files later.
