### ISSUE TITLE
Sectionless URLs and disambiguation pages

### ISSUE THREAD

**Issue by lassik** [schemedoc/manpages#8]
The Common Lisp HyperSpec has disambiguation pages like this: http://www.lispworks.com/documentation/HyperSpec/Body/a_list.htm

> Please select which reference to LIST you intended:
>
> * Function
> * System Class
> * Glossary Entry

We could have URLs like `https://man.scheme.org/values/` go to a disambiguation page like that.

Or we could do that the Unix `man` program does, and have a precedence order for sections. If a page name is found in multiple sections, and no section is specified, the page in the highest-precedence section is visited.

**Comment by lassik** [comment]
Let's do the following:

* Use `https://man.scheme.org/3scheme/values/` as primary URLs for the pages.
* Also add sectionless URLs like `https://man.scheme.org/values/`.
* Make the sectionless URLs do a HTTP redirect into the full URLs.
* In the case of duplicate page names, make the sectionless URL a disambiguation page instead of a redirect.

I'll write a Scheme script to auto-generate the redirects for `nginx.conf`.

**Comment by lassik** [comment]
Ref #7

**Comment by APIPLM** [comment]
It already is done in then `elisp `of Emacs. Like you are looking `pcase` by pressing `ATL+>`. It pops out

```
(feature pcase)
(defun pcase)
```

**Comment by lassik** [comment]
Interesting. What's the name of the Emacs function that does that?

**Comment by APIPLM** [comment]
`xref-find-definitions`

**Comment by lassik** [comment]
Closing for the same reason as https://github.com/schemedoc/manpages/issues/7#issuecomment-1445367579.
